- name: Update apt packages
  become: yes
  apt:
    name: "*"
    state: latest
    update_cache: yes
    force_apt_get: yes

- name: Installation of basics packages
  become: yes
  apt:
    state: latest
    name:
      - git
      - tree
      - htop
      - curl
      - emacs
      - net-tools
      - sudo
      - make
      - unzip
      - python3
      - python3-pip
